name: Flutter CI/CD

on:
  push:
    branches:
      - firebase
  pull_request:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4

      - name: Install Dependencies
        run: flutter pub get

      - name: Get Commit Hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Buat Folder Assets Release
        run: mkdir -p assets/release

      - name: Pindahkan APK ke Assets Release dengan Nama Berformat
        run: mv build/app/outputs/flutter-apk/app-release.apk assets/release/app-release-${{ env.COMMIT_HASH }}.apk

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: Flutter APK ${{ env.COMMIT_HASH }}
          path: assets/release/app-release-${{ env.COMMIT_HASH }}.apk

      - name: Create GitHub Release using GitHub API
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/releases \
          -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{
            "tag_name": "v1.0.${{ github.run_number }}-${{ env.COMMIT_HASH }}",
            "name": "Release v1.0.${{ github.run_number }}-${{ env.COMMIT_HASH }}",
            "body": "🚀 **Flutter APK Release**\n- Commit: `${{ env.COMMIT_HASH }}`\n- Branch: `${{ github.ref_name }}`",
            "draft": false,
            "prerelease": false
          }'

